# Generated by Django 6.0 on 2025-12-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Уникальный идентификатор пользователя в Telegram",
                        null=True,
                        unique=True,
                        verbose_name="ID в Telegram",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="@username пользователя",
                        max_length=100,
                        verbose_name="Username в Telegram",
                    ),
                ),
                (
                    "telegram_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя в Telegram"
                    ),
                ),
                (
                    "telegram_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия в Telegram"
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Получать ли уведомления о задачах",
                        verbose_name="Уведомления включены",
                    ),
                ),
                (
                    "daily_reminder_time",
                    models.TimeField(
                        default="09:00", verbose_name="Время ежедневного напоминания"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Часовой пояс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "ordering": ["user__username"],
            },
        ),
    ]
